//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPProjectDesign
{
    using System;
    using System.Collections.Generic;
    
    public partial class sell
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> quantity { get; set; }
        public string company { get; set; }
        public Nullable<int> mid { get; set; }
        public Nullable<int> code { get; set; }
    
        public virtual mobile mobile { get; set; }
    }
}
